name: Generate Podcast Feeds user 1 
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v3
   - name: Run Feed Generator
     uses: Rusmore/podcast-user1-gernerator@main
